apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
helmCharts:
  - name: hello-world
    releaseName: hello-world
    repo: https://helm.github.io/examples
    version: 0.1.0
    includeCRDs: true
    valuesInline:
      replicaCount: 2
